### ISSUE TITLE
ShopStock2.0.1&ShopBuyByCategory1.0.0とTMItemCategoryEx1.0.1の併用でカテゴリが反映されない

### ISSUE THREAD

**Issue by nyatama** [elleonard/RPGtkoolMV-Plugins#3]
にゃたまです。ツクマテのほうでは失礼しました。
初issues失礼します。やり方が間違っていたらすみません。
ご迷惑おかけしますがよろしくおねがいします。

Mac版ツクールMVのバージョンは1.6.2で確認しています。
TMItemCategoryEx 1.0.1
DarkPlasma_ShopBuyByCategory 1.0.0
DarkPlasma_ShopStock 2.0.1
の順でプラグインリストに配置していますが
購入時カテゴリそのものはTMItemCategoryExのカテゴリが表示されますが
カテゴリを選択すると何故かすべてのカテゴリでショップの処理で指定した
同じアイテムが表示されるようです。
売却時の問題はありません。

別件でプラグインパラメータの在庫リストID指定変数がデフォ状態(指定なし)
だと在庫表示されませんでした。
このときプラグインパラメータのショップ在庫設定には在庫リストID1に
在庫アイテムリストID１（ポーション）を指定してある状態です。
その他の値は変更していません。

在庫リストID指定変数に、ゲーム変数９を指定してそこに１を代入してから
実行すると在庫は表示されます。

それではよろしくおねがいします。

**Comment by elleonard** [comment]
ご報告ありがとうございます。

> TMItemCategoryEx 1.0.1
> DarkPlasma_ShopBuyByCategory 1.0.0
> DarkPlasma_ShopStock 2.0.1
> の順でプラグインリストに配置していますが
> 購入時カテゴリそのものはTMItemCategoryExのカテゴリが表示されますが
> カテゴリを選択すると何故かすべてのカテゴリでショップの処理で指定した
> 同じアイテムが表示されるようです。

DarkPlasma_ShopBuyByCategory.js のヘルプにも記載してある通り、このプラグインは DarkPlasma_ShopStock.js と併用する場合はそれよりも下に配置していただくことを想定しています。
その順番にした状態でも同じ症状が出るかどうかご確認ください。

> 別件でプラグインパラメータの在庫リストID指定変数がデフォ状態(指定なし)
> だと在庫表示されませんでした。

バグでしたので、2.0.3で修正いたしました。新しいバージョンをお試しください。

**Comment by nyatama** [comment]
お返事ありがとうございます。

> DarkPlasma_ShopBuyByCategory.js のヘルプにも記載してある通り、このプラグインは DarkPlasma_ShopStock.js と併用する場合はそれよりも下に配置していただくことを想定しています。

DarkPlasma_ShopBuyByCategoryの1.0.0にはヘルプに配置順のことは記載されてないように見えます。

それとTMItemCategoryExのファイル名を変更すると正常に動作しないので
ファイル名を変更しない方針にします。

> バグでしたので、2.0.3で修正いたしました。新しいバージョンをお試しください。

修正を確認しました。ありがとうございました。

**Comment by elleonard** [comment]
> DarkPlasma_ShopBuyByCategoryの1.0.0にはヘルプに配置順のことは記載されてないように見えます。

なんと！ 大変失礼しました。ローカルで書いてそのままコミットしておりませんでした。
説明を追加いたしました。

> それとTMItemCategoryExのファイル名を変更すると正常に動作しないので
> ファイル名を変更しない方針にします。

実は、外部からフックして対応することは可能です。
下記のコードを自前プラグインに入れていただき、 DarkPlasma_ShopBuyByCategory よりも下に読み込んでいただければ動作するかと。
```
Window_ShopBuy.prototype.isExtraCategoryEnabled = function () {
  return PluginManager.isLoadedPlugin(プラグイン名);
};
```

**Comment by nyatama** [comment]
Window_ShopBuy.prototype.isExtraCategoryEnabled = function () {
    return PluginManager.isLoadedPlugin('NYA_TMItemCategoryEx');
  };
のようにしてShopStockの'use strict'下に貼り付けましたが変化なしのようです…
配置順もShopStock→ShopBuyByCategory→NYA_TMItemCategoryExにしました。
やはりファイル名を変更することは無理っぽそうですね…

追記
すみません。自前プラグインってのはNYA_TMItemCategoryExのほうでしょうか？
いずれにせよこれはやはりファイル名を変更という行為自体がタブーなんだろうなぁ…

**Comment by elleonard** [comment]
`isExtraCategoryEnabled` 関数は DarkPlasma_ShopBuyByCategory の中に定義してありますので、その後に読み込むプラグインに再定義しないと意味がありません。
自前プラグインは改造されたTMItemCategoryExでも良いですが、それに限らず適当な新規プラグインでも構いません。

**Comment by nyatama** [comment]
ありがとうございます。とても勉強になりました。
とりあえず本件は解決ということにさせていただきます。
