### ISSUE TITLE
ShopStockの件でお聞きします

### ISSUE THREAD

**Issue by nyatama** [elleonard/RPGtkoolMV-Plugins#4]
にゃたまです。いつもお世話になります。毎度すみません。
DarkPlasma_ShopStockの件でお聞きしたいのですが、
普段は通常価格で売っているアイテムをそれとは
別に特売品価格で数量限定で販売するようなことはできるのでしょうか？

**Comment by nyatama** [comment]
すみません。考えたら別番号で同じアイテムを作ってそれぞれ価格変えればいいだけの話でした。
解決ということにします。

**Comment by nyatama** [comment]
なんども申し訳ないです。IDを違うもので別に作ると持っている数が
別扱いになってしまうことが判明しました。
やはり同じアイテムで異なる価格とアイテム名を「特価」などのタグつけて
同時販売するようなことは難しいでしょうか？

**Comment by elleonard** [comment]
> 普段は通常価格で売っているアイテムをそれとは
> 別に特売品価格で数量限定で販売するようなことはできるのでしょうか？

このプラグインはあくまで在庫設定プラグインであるため、価格の設定までは機能に含まれていません。
RPGツクールMV標準の機能で価格の設定自体は行えるので、数量限定の特別価格は、在庫リストID指定変数でショップのイベントそのものを分岐させる形で実現可能です。

また、在庫数は在庫リストの中のアイテムIDに対して設定していますので、同一画面上で在庫の異なる同一アイテムを複数販売することは現状のままではできません。

**Comment by elleonard** [comment]
在庫リスト設定の中に、アイテムIDとは別に在庫アイテムIDのような概念を導入する方針で改修すれば実現は可能と思われます。
むしろ、最初からそう設計すべきでしたね……。

**Comment by nyatama** [comment]
提案いただきありがとうございます。回収は大掛かりになりような予感がするので
大変であれば無理に対応しなくても構いません。できたらいいな程度だったんで。
逆に気を使わせてしまい申し訳ありませんでした。
なんとか別のアプローチも考えてみます。
でももし改修して可能になるようであれば是非使わせていただきます。
とりあえずこのissuesはこれで閉じておきます。ありがとうございました。
