### ISSUE TITLE
ShopStock&ShopBuyByCategoryとTMItemCategoryEx併用時の表示上の問題

### ISSUE THREAD

**Issue by nyatama** [elleonard/RPGtkoolMV-Plugins#5]
本当に何度もすみません。
表示上の問題でバグではないかもしれませんが一応報告しておきます。
ShopStock&ShopBuyByCategoryとTMItemCategoryEx併用時
ショップからアイテムを購入しようとすると数量ウィンドウの
上部分が切れるようです。ちょっとしたことですみません。
お暇なときで結構ですので確認いただけませんでしょうか？
これら３つのプラグイン有効時に発生するようです。
お手数おかけしますがよろしくおねがいします。

**Comment by nyatama** [comment]
売却時も同様にウィンドウサイズがおかしくなるようです。

**Comment by elleonard** [comment]
ご報告ありがとうございます。
レイアウトが崩れているようでしたので、修正した1.0.1を公開しました。

**Comment by nyatama** [comment]
修正を確認しました。何度もお手を煩わせてしまいすみません。
ありがとうございました。
